CREATE database AT2BDESNOITE;
USE AT2BDESNOITE;

CREATE TABLE FAIXA_IMOVEL
(CDFAIXA INT primary KEY,
NMFAIXA VARCHAR(30),
VLMINIMO DECIMAL(14,2),
VLMAXIMO DECIMAL(14,2));

CREATE TABLE ESTADO
(SGESTADO CHAR(2) primary KEY,
NMESTADO VARCHAR(20));

CREATE TABLE CIDADE 
(CDCIDADE INT,
SGESTADO CHAR(2),
NMCIDADE VARCHAR(20),
primary key (CDCIDADE,SGESTADO));

CREATE TABLE BAIRRO
(CDBAIRRO INT,
CDCIDADE INT,
SGESTADO CHAR(2),
NMBAIRRO VARCHAR(20),
primary key (CDBAIRRO,CDCIDADE,SGESTADO));

CREATE TABLE COMPRADOR
(CDCOMPRADOR INT PRIMARY KEY,
NMCOMPRADOR VARCHAR(40),
NMENDERECO VARCHAR(40),
NRCPF DECIMAL(11),
NMCIDADE VARCHAR(20),
NMBAIRRO VARCHAR(20),
SGESTADO CHAR(2),
TELEFONE VARCHAR(14),
EMAIL VARCHAR(100));

CREATE TABLE VENDEDOR
(CDVENDEDOR INT PRIMARY KEY,
NMVENDEDOR VARCHAR(40),
NMENDERECO VARCHAR(40),
NRCPF DECIMAL(11),
NMCIDADE VARCHAR(20),
NMBAIRRO VARCHAR(20),
SGESTADO CHAR(2),
TELEFONE VARCHAR(14),
EMAIL VARCHAR(100));

CREATE TABLE IMOVEL (
  CDIMOVEL INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CDBAIRRO INT,
  CDCIDADE INT,
  SGESTADO CHAR(2),
  CDVENDEDOR INT,
  NMENDEREÇO  VARCHAR(40) NULL,
  NRAREAUTIL DECIMAL(10,2) NULL,
  NRAREATOTAL DECIMAL(10,2) NULL,
  DSIMOVEL VARCHAR(300) NULL,
  VLPRECO DECIMAL(16,2) NULL,
  NROFERTAS INTEGER UNSIGNED NULL,
  STVENDIDO CHAR(1) NULL,
  DTLANCTO DATE NULL,
  IMOVEL_INDICADO INT UNSIGNED NULL,
  primary key (CDIMOVEL),
CONSTRAINT IMOVEL  foreign key (CDBAIRRO,CDCIDADE,SGESTADO) REFERENCES BAIRRO (CDBAIRRO,CDCIDADE,SGESTADO),
CONSTRAINT IMOVEL1 foreign key(CDVENDEDOR) references VENDEDOR (CDVENDEDOR),
CONSTRAINT IMOVEL2 foreign key (IMOVEL_INDICADO) REFERENCES IMOVEL(CDIMOVEL)
);


CREATE TABLE OFERTA
(CDIMOVEL INT UNSIGNED NOT NULL,
CDCOMPRADOR INT,
VLOFERTA DECIMAL(16,2),
DTOFERTA DATE,
primary key (CDIMOVEL, CDCOMPRADOR),
CONSTRAINT OFERTA FOREIGN KEY(CDCOMPRADOR) REFERENCES COMPRADOR(CDCOMPRADOR),
CONSTRAINT OFERTA1 FOREIGN KEY(CDIMOVEL) REFERENCES IMOVEL(CDIMOVEL)
);
  
     